### ISSUE TITLE
KSM Solver choice and iteration count

### ISSUE THREAD

**Issue by A-CGray** [smdogroup/tacs#4]
We currently have an implementation of a nonlinear solver which works with the old version of TACS that I am attempting to transfer over to this newer version. In our solver, we check the number of iterations taken during each linear solve in order to decide whether to update the preconditioner. This was done using a `getIterCount` method inside the GCROT class, this method was not implemented in the GMRES or PCG classes although as far as I can see there is an iteration counting variable that could be output.

The problem I am running into now is that although GCROT, GMRES and PCG are all still defined in KSM.cpp, the python interface is currently hardcoded to return a GMRES object when asked for a KSM:
```python
cdef class KSM:
    def __cinit__(self, Mat mat, Pc pc, int m,
                  int nrestart=1, int isFlexible=0):
        '''
        Create a GMRES object for solving a linear system with or
        without a preconditioner.

        This automatically allocates the requried Krylov subspace on
        initialization.

        input:
        mat:        the matrix operator
        pc:         the preconditioner
        m:          the size of the Krylov subspace
        nrestart:   the number of restarts before we give up
        isFlexible: is the preconditioner actually flexible? If so use FGMRES
        '''

        self.ptr = new GMRES(mat.ptr, pc.ptr, m, nrestart, isFlexible)
        self.ptr.incref()
        return

    def __dealloc__(self):
        if self.ptr:
            self.ptr.decref()
        return
```
I therefore have 2 questions:
- Are there some bugs with GCROT and PCG that are behind the reason for making only GMRES available through the python interface?
- If not, do you have anything against me adding the functionality to choose different KSM's through the interface and also adding a `getIterCount` method to each one?

Thanks

Ali

**Comment by gjkennedy** [comment]
GMRES is the default in python since we tend to use it as a wrapper around a direct solver. PCG and GCROT could also be wrapped in python. GCROT is more specialized, and has more parameters that require tuning, which is why I left it out of the wrapper. Wrapping either should be straightforward.

Querying the number of iterations and wrapping it is a bit more complicated. It should perhaps be a virtual function in the base KSM class or, I think, returned from the TACSKsm::solve function. Otherwise, you'll have to cast the python-wrapped KSM pointer to GMRES/GCROT/PCG type.
